"""Autonomous pipeline with source, review, test, and publication gates."""
import asyncio
import json
import time
from datetime import datetime
from pathlib import Path
from sqlalchemy import update
from git import Repo
from agents.agent1_scanner import run_scanner
from agents.agent2_patcher import run_patcher,commit_patches,repair_regressions,repair_review_findings
from agents.agent3_reviewer import run_reviewer
from agents.agent4_tester import run_baseline_tester,run_tester
from services.github_service import push_branch,create_pull_request
from services.repository import scan_directory,redact
from core.database import AsyncSessionLocal
from core.redis_client import publish_event,set_scan_state
from core.config import settings
from models.scan_job import ScanJob,ScanStatus,AgentStatus

_pipeline_lock = asyncio.Lock()

async def _update_job(scan_id,**fields):
    async with AsyncSessionLocal() as db:
        await db.execute(update(ScanJob).where(ScanJob.id==scan_id).values(**fields))
        await db.commit()

async def emit_pipeline(scan_id,message,data=None,level='info'):
    await publish_event(scan_id,{'agent':'orchestrator','message':redact(message),'data':data or {},'level':level})

def build_pr_description(scan_id,findings,patches,review,tests,base_sha,patch_sha):
    before,after = tests['original_tests'],tests['patched_tests']
    issues = '\n'.join(f"- {v.get('cwe_id') or v.get('cve_id') or v['category']}: `{v['file']}` — {v['message']}" for v in findings)
    models = ', '.join(sorted({p['model_used'] for p in patches}))
    fixed = '\n'.join('- `'+name+'`' for name in tests.get('fixed_tests',[])) or '- No pre-existing failing tests changed status.'
    return f'''## Security issue and fix
{issues}

The patch binds SQL values, enforces filesystem boundaries, or validates object
ownership as applicable to the findings above. Inspect the file diffs for the
specific changes. Source checks used the same rules before and after patching.

## Executed test evidence
| Metric | Before | After |
|---|---:|---:|
| Passed | {before['passed']} | {after['passed']} |
| Failed | {before['failed']} | {after['failed']} |
| Errors | {before['errors']} | {after['errors']} |
| Collected tests | {before['total']} | {after['total']} |

- Runner: `{after['runner']}`
- Security tests passed: {tests['security_tests_count']}
- Previously passing tests retained: {not tests['regressions']}
- Missing tests: {len(tests['missing_tests'])}
- Final source findings: {len(review['remaining_findings'])}
- Model / repair engine: `{models}`
- Validation score: {tests.get('verification_score',0)}/100 (executed checks; not a probability)
- Changed source lines: {tests.get('changed_lines','unknown')}
- Base commit: `{base_sha}`
- Validated patch commit: `{patch_sha}`
- Scan ID: `{scan_id}`

Tests that failed on the vulnerable baseline and now pass:
{fixed}

Generated by VASUKI. This draft PR includes automated evidence for human review.
'''

async def run_full_pipeline(scan_id,repo_url,branch=None,project_path='',bundled=False,publish_pr=True):
    # Micro VM: avoid running multiple model/test jobs against limited memory.
    await emit_pipeline(scan_id,'Queued for the next available pipeline runner',{'status':'pending'})
    async with _pipeline_lock:
        await _run(scan_id,repo_url,branch,project_path,bundled,publish_pr)

async def _run(scan_id,repo_url,branch,project_path,bundled,publish_pr):
    started=time.monotonic()
    active='scanner'
    evidence={'source':'bundled' if bundled else 'github','project_path':project_path,'publish_pr':publish_pr}
    patches=[]
    notes={}
    async def stage(status,agent,progress,message):
        nonlocal active
        active=agent
        await _update_job(scan_id,status=status,**{'agent_'+agent:AgentStatus.RUNNING})
        await set_scan_state(scan_id,{'status':status.value,'active_agent':agent,'progress':progress})
        await emit_pipeline(scan_id,message,{'progress':progress,'active_agent':agent})
    async def finish(status,message):
        checks={
            'source_rescan_clear':notes.get('all_findings_resolved') is True,
            'patched_suite_passed':evidence.get('patched_tests',{}).get('success') is True,
            'baseline_coverage_preserved':evidence.get('regression_free') is True,
            'security_exploits_blocked':evidence.get('security_tests_passed') is True,
            'diff_within_limit':bool(patches) and evidence.get('changed_lines',settings.MAX_TOTAL_CHANGED_LINES+1)<=settings.MAX_TOTAL_CHANGED_LINES,
        }
        evidence['verification_checks']=checks
        evidence['verification_score']=20*sum(checks.values())
        evidence['elapsed_seconds']=round(time.monotonic()-started,2)
        evidence['outcome']=message
        (scan_directory(scan_id)/'evidence.json').write_text(json.dumps(evidence,indent=2),encoding='utf-8')
        await _update_job(scan_id,status=status,test_results=evidence,confidence_score=evidence['verification_score'],completed_at=datetime.utcnow(),
                          error_message=message if status!=ScanStatus.COMPLETED else '')
        await set_scan_state(scan_id,{'status':status.value,'progress':100,'message':message})
        await emit_pipeline(scan_id,message,{'status':status.value,'progress':100},
                            'info' if status==ScanStatus.COMPLETED else 'error')
    try:
        await stage(ScanStatus.SCANNING,'scanner',8,'RECON: cloning and analyzing repository')
        result=await run_scanner(repo_url,scan_id,branch,project_path,bundled)
        repo_path,project_root=result['repo_path'],result['project_root']
        findings=result['vulnerabilities']
        evidence.update({'base_sha':result['base_sha'],'branch':result['branch'],'scanner':'native-ast+semgrep' if settings.SCANNER_MODE=='semgrep' else 'native-ast'})
        await _update_job(scan_id,branch=result['branch'],agent_scanner=AgentStatus.DONE,
                          vulnerabilities=findings,blast_radius=result['blast_radius'])
        if not findings:
            await finish(ScanStatus.COMPLETED,'No findings returned by the configured source analyzer')
            return
        baseline=await run_baseline_tester(project_root,scan_id,trusted=bundled)
        evidence['original_tests']=baseline
        await _update_job(scan_id,test_results=evidence)
        if not baseline.get('cases') or baseline.get('error') or baseline.get('errors'):
            await finish(ScanStatus.BLOCKED,'Baseline tests could not run successfully; configure dependencies and Docker before retrying')
            return
        await stage(ScanStatus.PATCHING,'patcher',30,'FORGE: generating targeted security patches')
        generated=await run_patcher(findings,repo_path,scan_id)
        patches=generated['patches']
        await _update_job(scan_id,agent_patcher=AgentStatus.DONE,patches=patches)
        if not patches:
            await finish(ScanStatus.BLOCKED,'No applicable patch was generated')
            return
        (scan_directory(scan_id)/'patch.diff').write_text(Repo(repo_path).git.diff(),encoding='utf-8')
        await stage(ScanStatus.REVIEWING,'reviewer',55,'SHIELD: verifying the final source and every applied patch')
        reviewed=await run_reviewer(patches,findings,scan_id,repo_path,project_root,bundled)
        notes=reviewed['review_notes']
        if not notes['all_findings_resolved'] or notes['summary']['rejected']:
            await emit_pipeline(scan_id,'Security review rejected the first patch; feedback returned to FORGE for one bounded repair',{'review':notes},level='warning')
            await _update_job(scan_id,agent_patcher=AgentStatus.RUNNING)
            if await repair_review_findings(repo_path,patches,notes,scan_id):
                evidence['review_repair_attempts']=1
                reviewed=await run_reviewer(patches,findings,scan_id,repo_path,project_root,bundled)
                notes=reviewed['review_notes']
            await _update_job(scan_id,agent_patcher=AgentStatus.DONE,patches=patches)
        await _update_job(scan_id,agent_reviewer=AgentStatus.DONE,review_notes=notes,confidence_score=reviewed['confidence_score'])
        if not notes['all_findings_resolved'] or notes['summary']['rejected'] or notes['summary']['approved']!=len(patches):
            await finish(ScanStatus.BLOCKED,'Security review rejected the patch set; unresolved findings are in the review report')
            return
        await stage(ScanStatus.TESTING,'tester',75,'PROOF: executing patched tests and comparing each baseline result')
        tested=await run_tester(project_root,patches,scan_id,baseline,bundled)
        evidence.update(tested['test_results'])
        if not evidence.get('regression_free') and evidence['patched_tests'].get('cases'):
            await emit_pipeline(scan_id,'Test feedback returned to FORGE for one bounded repair attempt')
            if await repair_regressions(repo_path,patches,evidence,scan_id):
                reviewed=await run_reviewer(patches,findings,scan_id,repo_path,project_root,bundled)
                notes=reviewed['review_notes']
                await _update_job(scan_id,review_notes=notes,confidence_score=reviewed['confidence_score'])
                if notes['all_findings_resolved'] and not notes['summary']['rejected']:
                    tested=await run_tester(project_root,patches,scan_id,baseline,bundled,attempt=2)
                    evidence.update(tested['test_results'])
                    evidence['repair_attempts']=1
                else:
                    await finish(ScanStatus.BLOCKED,'Regression repair did not pass the repeated security review')
                    return
        await _update_job(scan_id,agent_tester=AgentStatus.DONE,test_results=evidence)
        if evidence.get('regression_free') is not True or evidence['patched_tests'].get('success') is not True:
            await finish(ScanStatus.BLOCKED,'Patched test suite failed or lost baseline coverage; publication blocked')
            return
        final_diff=Repo(repo_path).git.diff()
        evidence['changed_lines']=sum(line[:1] in {'+','-'} and not line.startswith(('+++','---')) for line in final_diff.splitlines())
        if evidence['changed_lines']>settings.MAX_TOTAL_CHANGED_LINES:
            await finish(ScanStatus.BLOCKED,'Final patch exceeded the configured diff limit; publication blocked')
            return
        evidence['verification_score']=20*sum([
            notes['all_findings_resolved'],evidence['patched_tests']['success'],evidence['regression_free'],
            evidence.get('security_tests_passed') is True,evidence['changed_lines']<=settings.MAX_TOTAL_CHANGED_LINES])
        if not await commit_patches(repo_path,f'{len(patches)} verified security patches',scan_id,sorted({p['file'] for p in patches})):
            await finish(ScanStatus.FAILED,'Verified patches could not be committed')
            return
        evidence['patch_sha']=Repo(repo_path).head.commit.hexsha
        for patch in patches:
            patch['final_diff']=Repo(repo_path).git.diff(result['base_sha'],'HEAD','--',patch['file'])
        await _update_job(scan_id,patches=patches)
        (scan_directory(scan_id)/'patch.diff').write_text(Repo(repo_path).git.diff(result['base_sha'],'HEAD'),encoding='utf-8')
        description=build_pr_description(scan_id,findings,patches,notes,evidence,result['base_sha'],evidence['patch_sha'])
        evidence['pr_description']=description
        (scan_directory(scan_id)/'pull-request.md').write_text(description,encoding='utf-8')
        if bundled or not publish_pr:
            await finish(ScanStatus.COMPLETED,'Verified patch committed. Evidence and patch are ready to download.')
            return
        active='github'
        await emit_pipeline(scan_id,'HERALD: publishing the verified branch and opening a draft PR',{'progress':95})
        if not await push_branch(repo_path,generated['branch_name'],repo_url,scan_id):
            await finish(ScanStatus.FAILED,'Patch verified, but branch push failed. Download the patch and evidence to recover it.')
            return
        pr=await create_pull_request(repo_url,generated['branch_name'],description,findings,reviewed['confidence_score'],scan_id,result['branch'])
        if not pr.get('pr_url'):
            await finish(ScanStatus.FAILED,'Branch pushed, but draft PR could not be created')
            return
        evidence['pr_url']=pr['pr_url']
        await _update_job(scan_id,pr_url=pr['pr_url'],pr_number=pr['pr_number'])
        await finish(ScanStatus.COMPLETED,'Verified patches published in a real GitHub draft PR')
    except Exception as exc:
        if active in {'scanner','patcher','reviewer','tester'}:
            await _update_job(scan_id,**{'agent_'+active:AgentStatus.ERROR})
        await finish(ScanStatus.FAILED,redact(f'{type(exc).__name__}: {exc}'))
